# Generated by Django 4.0.2 on 2022-02-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='signature_time',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
