# Generated by Django 4.0.2 on 2022-02-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_signature_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='signature_time',
            field=models.DateTimeField(null=True),
        ),
    ]
