# Generated by Django 4.0.2 on 2022-02-14 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_comments_event_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 11, 57, 31, 677404)),
        ),
    ]
