# Generated by Django 4.0.2 on 2022-02-17 13:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0003_alter_contract_signature_time'),
        ('event', '0003_event_attendees_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 14, 19, 10, 116539)),
        ),
    ]
