# Generated by Django 4.0.2 on 2022-02-20 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_assignee_alter_event_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 21, 10, 26, 39540)),
        ),
    ]
